language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6

env:
  - RAILS_ENV=test
script:
- gem install bundler:2.1.4
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
on:
  repo: austin/rails-engine
  branch: main
skip_cleanup: 'true'
