language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- gem install bundler:2.1.4
- bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
- bundle exec rails db:schema:dump 
- bundle exec rspec
on:
  repo: austin/rails-engine
  branch: main
skip_cleanup: 'true'
