language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6

env:
  - RAILS_ENV=test
script:
- gem install bundler --conservative
- bundle install --frozen
- bundle exec rails db:create db:schema:load db:test:prepare
- bundle exec rspec
on:
  repo: austin/rails-engine
  branch: main
skip_cleanup: 'true'
