language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
cache:
  bundler: true
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
on:
  repo: austin/rails-engine
  branch: main
skip_cleanup: 'true'
